# Generated by Django 6.0.6 on 2026-06-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title (e.g., duck-til-dun)', unique=True)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Development', 'In Development'), ('Released', 'Released')], default='In Development', max_length=50)),
                ('cover_image_url', models.URLField(blank=True, help_text='Link to game poster or asset art')),
            ],
        ),
    ]
