# Generated by Django 6.0.6 on 2026-06-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_image_url',
            field=models.CharField(blank=True, help_text='Relative path (e.g., /games/image.png) or full URL to game poster', max_length=500),
        ),
    ]
